services:
  postgres:
    image: postgres:16-alpine
    container_name: cinema_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
      POSTGRES_DB: cinema_db
    # Dont ever open the ports of the DB
    #ports:
    #- "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cinema_frontend
    restart: unless-stopped
    command: bun dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - postgres

  backend:
    container_name: cinema_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: php artisan serve --host=0.0.0.0 --port=8000

  realtime:
    build:
      context: ./realtime
      dockerfile: Dockerfile.dev
    container_name: cinema_realtime
    restart: unless-stopped
    command: bun index.ts
    ports:
      - "3001:3001"
    volumes:
      - ./realtime:/app
      - /app/node_modules
    depends_on:
      - postgres

  # For now i dont need nginx, will bring it back up in prod
  #nginx:
  #  image: nginx:alpine
  #  container_name: cinema_nginx
  #  restart: unless-stopped
  #  ports:
  #    - "8080:80"
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./backend:/var/www/backend:ro
  #    - ./frontend:/var/www/frontend:ro
  #  depends_on:
  #    - backend
  #    - frontend
  #  networks:
  #    - cinema_network

volumes:
  postgres_data:
